apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: gcp-secret-store
  namespace: default
spec:
  provider:
    gcpsm:
      projectID: "ray-distributed-ml" 
      auth:
        workloadIdentity:
          clusterLocation: "europe-west1-b"
          clusterName: "ray-gpu-cluster"
          serviceAccountRef:
            name: eso-ksa
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mlflow-db-password-sync
  namespace: default
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: gcp-secret-store
    kind: SecretStore
  target:
    name: mlflow-db-password 
    creationPolicy: Owner
  data:
  - secretKey: password 
    remoteRef:
      key: mlflow-db-password 
      version: latest